Made the arachni script a little smarter to init the db and print default creds to stdout

diff --git a/dockerfunc b/dockerfunc
--- a/dockerfunc
+++ b/dockerfunc
@@ -415,22 +415,28 @@ d_nikto() {
 
 d_arachni() {
     _docker_relieson "postgres"
+    sleep 1
     docker exec -ti postgres sh -c "psql -lqt | cut -d \| -f 1 | grep -qw arachni_production" > /dev/null 2>&1
-    if [[ $? != 0 ]]; then
+    if [[ $? -ne 0 ]]; then
       echo "database doesn't exist. creating"
       docker run \
         --rm \
         --link postgres \
         -e POSTGRES_PASSWORD=pass -e POSTGRES_USERNAME=root -e POSTGRES_DATABASE=arachni_production \
         -ti \
-        treadie/arachni sh -c "/opt/arachni/bin/arachni_web_task db:setup arachni"
+        treadie/arachni sh -c "/opt/arachni/bin/arachni_web_task db:setup"
     fi
-	if [ "${1}" = "l" ]; then _docker_logwrap "${FUNCNAME[0]}"; return; fi
-	docker run \
-      --rm \
-      --link postgres \
-      -p 9292:9292 \
-      -e POSTGRES_PASSWORD=pass -e POSTGRES_USERNAME=root -e POSTGRES_DATABASE=arachni_production \
-      -ti \
-      treadie/arachni
+    if [[ $? -eq 0 ]]; then
+      if [ "${1}" = "l" ]; then _docker_logwrap "${FUNCNAME[0]}"; return; fi
+      echo "default creds: admin@admin.admin / administrator"
+      docker run \
+        --rm \
+        --link postgres \
+        -p 9292:9292 \
+        -e POSTGRES_PASSWORD=pass -e POSTGRES_USERNAME=root -e POSTGRES_DATABASE=arachni_production \
+        -ti \
+        treadie/arachni
+    else
+      echo "Encountered an error (presumably with the DB). Did not attempt to run app"
+    fi
 }
